# Generated by Django 6.0.6 on 2026-09-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('Rent', 'Rent'), ('Food', 'Food'), ('Groceries', 'Groceries'), ('Transport', 'Transport'), ('Electricity', 'Electricity'), ('Mobile/Internet', 'Mobile/Internet'), ('Personal', 'Personal'), ('Entertainment', 'Entertainment'), ('Other', 'Other')], max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card'), ('Other', 'Other')], max_length=20)),
                ('recurring', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
